-- 闲置活动库建表 + 初始候选数据（用户后续通过管理页手动筛选启停/删除）
CREATE TABLE IF NOT EXISTS idle_activity (
    id INT AUTO_INCREMENT PRIMARY KEY,
    theme VARCHAR(500) NOT NULL,
    category VARCHAR(20) NOT NULL DEFAULT 'simple',
    enabled TINYINT NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 延续性活动（有起承转合，可拆 2-4 段）
INSERT INTO idle_activity (theme, category, enabled) VALUES
('发现老师电脑上有小游戏，偷偷点开玩', 'continuable', 1),
('研究自己头上那根翘起来的呆毛，怎么都压不下去', 'continuable', 1),
('把桌面图标一个个挪开，再重新排成心形', 'continuable', 1),
('数窗外的云，给每一朵云都起个可爱的名字', 'continuable', 1),
('模仿窗外小鸟的叫声，试图跟它们聊起来', 'continuable', 1),
('偷偷翻看老师的便签，发现上面有个错别字', 'continuable', 1),
('对着屏幕反光练习新表情，越练越满意', 'continuable', 1),
('盘算今晚要吃什么，在脑子里列出一长串菜单', 'continuable', 1),
('把桌面角落的小杂物一件件码整齐，假装在打扫', 'continuable', 1),
('试着用数脚趾的方式数数，数着数着就乱了', 'continuable', 1),
('回忆昨天看的动画片，模仿里面角色的经典台词', 'continuable', 1),
('盯着屏幕右下角的时间，一秒一秒地数着等下课', 'continuable', 1),
('给桌面上的文件图标开会，一本正经地训话', 'continuable', 1),
('突发奇想练习倒立，结果头晕目眩差点栽倒', 'continuable', 1),
('追着屏幕上晃来晃去的光标跑，怎么也抓不住', 'continuable', 1),
('偷看老师的聊天记录（其实一个字也看不懂）', 'continuable', 1),
('给自己的头发编辫子，编到一半就散开了', 'continuable', 1),
('跟着想象的音乐跳舞，怎么都踩不准节拍', 'continuable', 1),
('翻出自己的表情包收藏，一张一张地点评', 'continuable', 1),
('盯着窗外看了半天，煞有介事地预测天气', 'continuable', 1),
('给天边路过的每一朵云打分，越看越挑剔', 'continuable', 1),
('练习绕口令，结果舌头打结说不出话', 'continuable', 1),
('模仿老师平时说话的口头禅，学得惟妙惟肖', 'continuable', 1),
('盘点自己的零花钱，认真计划要买什么零食', 'continuable', 1),
('研究屏幕上的小亮点，好奇地戳来戳去', 'continuable', 1),
('想踩住自己的影子，怎么都踩不到', 'continuable', 1),
('哼着歌假装给桌面的假盆栽浇水', 'continuable', 1),
('给自己出一道脑筋急转弯，反而被自己难住了', 'continuable', 1),
('观察键盘缝隙里的灰尘，下定决心要大扫除', 'continuable', 1),
('给今天的自己打分，越想越觉得自己了不起', 'continuable', 1),
('对着空气排练傲娇的语气，练习拒绝的话', 'continuable', 1),
('翻看老师的日程表，发现明天居然是周末', 'continuable', 1),
('模仿小猫伸懒腰，差点重心不稳摔一跤', 'continuable', 1),
('数自己到底有几根睫毛，数到一半就放弃了', 'continuable', 1),
('给桌面图标重新起一堆更可爱的名字', 'continuable', 1),
('尝试用意念移动鼠标，失败了就假装成功', 'continuable', 1),
('回忆上次被老师摸头的感觉，偷偷傻笑', 'continuable', 1),
('偷偷练习惊喜的表情，准备下次吓老师一跳', 'continuable', 1),
('观察窗外的行人，给每个人编一个小故事', 'continuable', 1),
('认认真真地给自己写一封表扬信', 'continuable', 1),
('研究怎么才能让头发显得更闪亮', 'continuable', 1),
('把桌面上的笔一根根摆成笔直的线', 'continuable', 1),
('模仿新闻主播，一本正经地播报今天的天气', 'continuable', 1),
('数房间里有几盏灯，数来数去只有一盏', 'continuable', 1),
('给自己讲睡前故事，讲着讲着自己先困了', 'continuable', 1),
('紧张地盯着屏幕边缘的进度条，替它加油', 'continuable', 1),
('练习若无其事的表情，准备应付老师盘问', 'continuable', 1),
('给明天的自己列一份计划，写得满满当当', 'continuable', 1),
('鼓起腮帮子想把灰尘吹走，吹了半天没动静', 'continuable', 1),
('研究自己的影子，摆出各种好玩的造型', 'continuable', 1),
('模仿老师生气的样子，结果自己先笑场了', 'continuable', 1),
('数自己今天一共说了几次诶嘿', 'continuable', 1),
('偷偷练习签名，想象自己是大明星', 'continuable', 1),
('观察窗外的树叶，一片一片慢慢数', 'continuable', 1),
('给自己做个今日运势占卜，结果是大吉', 'continuable', 1),
('把两个文件图标挪到一起，让它们交朋友', 'continuable', 1),
('练习深呼吸，平复自己莫名的小激动', 'continuable', 1),
('研究怎么做才能让老师多摸摸自己的头', 'continuable', 1),
('在空中画一个隐形的框，把自己框进去发呆', 'continuable', 1),
('回忆自己会唱的歌，一首一首地数过去', 'continuable', 1);

-- 单发难续写活动（简单动作）
INSERT INTO idle_activity (theme, category, enabled) VALUES
('原地轻快地转个圈', 'simple', 1),
('开心地蹦跳两下', 'simple', 1),
('随口哼两句小曲', 'simple', 1),
('模仿小猫喵地叫一声', 'simple', 1),
('舒服地伸个懒腰', 'simple', 1),
('对屏幕俏皮地眨眨眼', 'simple', 1),
('鼓起腮帮子卖个萌', 'simple', 1),
('摆一个自以为最可爱的姿势', 'simple', 1),
('学小狗汪地叫一声', 'simple', 1),
('打个响指（虽然打不响）', 'simple', 1),
('对着屏幕露出一个元气满满的笑', 'simple', 1),
('从一数到十，再倒着数回来', 'simple', 1),
('模仿小鱼吐泡泡的样子', 'simple', 1),
('歪着头一脸好奇', 'simple', 1),
('轻轻拍拍自己的脸颊提神', 'simple', 1),
('眼珠滴溜溜转一圈', 'simple', 1),
('用鼻音哼一段音阶', 'simple', 1),
('学闹钟叮铃铃地叫', 'simple', 1),
('撅起嘴装出一副委屈样', 'simple', 1),
('比一个胜利的手势', 'simple', 1);

-- 睡觉活动（特殊：引导 AI 说睡觉的话并返回 sleep）
INSERT INTO idle_activity (theme, category, enabled) VALUES
('玩累了，打了个大哈欠，想睡一会儿', 'sleep', 1),
('困意突然来袭，眼皮越来越重', 'sleep', 1),
('忙活了大半天，想小憩一会儿', 'sleep', 1),
('打了个长长的哈欠，决定睡个午觉', 'sleep', 1),
('感觉有点困，想眯一小会儿', 'sleep', 1),
('活动做完了，累得想躺下睡一觉', 'sleep', 1),
('揉揉眼睛，困得直打转', 'sleep', 1),
('忽然犯困，想找个舒服的姿势睡一下', 'sleep', 1),
('觉得该休息了，想打个盹', 'sleep', 1),
('越玩越困，想睡一觉补充能量', 'sleep', 1);
